/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import rhinoVertexShader from './vertex.glsl'
import rhinoFragmentShader from './fragment.glsl'
import { useEffect, useMemo, useRef } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function AriesConstellation(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/aries-constellation-thin.glb')

  const { gl } = useThree();
  gl.setPixelRatio(Math.min(window.devicePixelRatio, 2))

  const uniforms = useMemo(() => ({
    uSize: { value: 0.1 },
    uTime: { value: 0 },
  }), []);

  const shaderRef = useRef();
  useFrame((state, delta) => {
    if (shaderRef.current) {
      // shaderRef.current.uniforms.uTime.value = state.clock.elapsedTime;
      shaderRef.current.uniforms.uSize.value = 400 * gl.getPixelRatio()
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={[1, 0.001, 1]} position={[0, -1, 0]} rotation={[Math.PI/2, 0, 0]}>
        {/* take position by a factor of dots in a ring */}
        {/* add one dot there */}
        <points geometry={nodes.BezierCurve001.geometry} >
          <shaderMaterial
            blending={THREE.AdditiveBlending}
            depthWrite={false}
            vertexColors={true}
            vertexShader={rhinoVertexShader}
            fragmentShader={rhinoFragmentShader}
            ref={shaderRef}
            uniforms={uniforms}
          />
        </points>
      </group>
    </group>
  )
}

useGLTF.preload('models/taurus-constellation-dhazele-2.glb')