/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import { Points } from "@react-three/drei";
import React from "react";
import { TextureLoader } from "three/src/loaders/TextureLoader";
import { useLoader } from "@react-three/fiber";

export default function Polaris2({ position, tile, scale }) {
  const points = useRef();
  const particleTexture = useLoader(TextureLoader, "/textures/particles/9.png");

  const parameters = {
    count: 1,
    size: 3,
    radius: 10,
  };

  const positions = new Float32Array(parameters.count * 3);

  for (let i = 0; i < parameters.count; i++) {
    const i3 = i * 3;
    positions[i3] = position[0];
    positions[i3 + 1] = position[1];
    positions[i3 + 2] = position[2];
  }

  return (
    <points ref={points}>
      <bufferGeometry>
        <bufferAttribute
          attach="attributes-position"
          count={positions.length / 3}
          array={positions}
          itemSize={3}
        />
      </bufferGeometry>
      {/* <sphereGeometry args={[1, 48, 48]} /> */}
      <pointsMaterial
        color="white"
        size={parameters.size}
        sizeAttenuation
        transparent
        alphaMap={particleTexture}
        // alphaTest={0.001}
        depthWrite={false}
      />
    </points>
  );
}
