/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { animated } from "@react-spring/three";

export default function Polaris({position, rotation, scale}) {
  const { nodes, materials } = useGLTF("/models/polaris.glb"); // lights
  return (
    <animated.group position={position} rotation={rotation} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={materials['Light Blue.001']}
        position={[-0.005, 0.018, -0.024]}
        scale={0.504}>
        <group
          position={[0.636, 0.63, 0.636]}
          rotation={[Math.PI, Math.PI / 4, -2.182]}
          scale={0.194}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035.geometry}
            material={materials['Dark Blue.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035_1.geometry}
            material={materials['Light Blue.001']}
          />
        </group>
        <group
          position={[0, 0, -1.111]}
          rotation={[Math.PI / 2, Math.PI / 4, -Math.PI]}
          scale={0.381}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035_2.geometry}
            material={materials['Dark Blue.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035_3.geometry}
            material={materials['Light Blue.001']}
          />
        </group>
        <group position={[1.111, 0, 0]} rotation={[Math.PI / 4, 0, -Math.PI / 2]} scale={0.381}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035_4.geometry}
            material={materials['Dark Blue.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035_5.geometry}
            material={materials['Light Blue.001']}
          />
        </group>
        <group position={[0, 1.111, 0]} rotation={[0, Math.PI / 4, 0]} scale={0.381}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035_6.geometry}
            material={materials['Dark Blue.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane035_7.geometry}
            material={materials['Light Blue.001']}
          />
        </group>
      </mesh>
    </animated.group>
  );
}
